# Generated by Django 5.1.6 on 2025-03-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0004_subscription_pemissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='pemissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['advanced', 'basic', 'pro', 'basic_ai'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
