# Generated by Django 5.1.6 on 2025-03-08 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='pemissions',
            new_name='permissions',
        ),
    ]
