# Generated by Django 5.1.6 on 2025-03-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_subscription_featured_subscription_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['subscription__order', 'order', 'featured', '-updated']},
        ),
    ]
