# Generated by Django 5.1.6 on 2025-03-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('advanced', 'Advanced Perm'), ('basic', 'Basic Perm'), ('pro', 'Pro Perm'), ('basic_ai', 'Basic AI Perm')]},
        ),
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['order', 'featured', '-updated']},
        ),
    ]
